eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
#      http://huaxin:123456@10.0.0.97:8000/eureka/
#         http://huaxin:123456@10.0.0.97:8000/eureka/
server:
  port: 6061
spring:
  application:
    name: service-feign
